### ISSUE TITLE
Do you need help to maintain ?

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi-sdk-javascript#74]
**Is your feature request related to a problem? Please describe.**
No.. Hmm Yes nobody want to maintain this SDK

**Describe the solution you'd like**
I'm here to try to maintain it or help to maintain it

**Describe alternatives you've considered**
Hmm don't chose me 😢 

**Additional context**
Pssss I'm French so be Nice 😄 

@soupette

**Comment by lauriejim** [comment]
Hello! In general we will need help for Docker, Strapi, SDK, FrontEnd solution connectors repos.
But for now we have to prepare that, write documentation to share with new maintainers the mindset/values we have in Strapi.
Since it's not finish it's difficult. Will let you know when we will be ready.

**Comment by Stun3R** [comment]
When It will be possible to help maintaining some strapi project could you please notify us  😄
