### ISSUE TITLE
Error: Too many attempts, please try again in a minute.

### ISSUE THREAD

**Issue by Shashi-GS** [strapi/strapi-sdk-javascript#77]
Node 10.x.x 
strapi version 3.0.0-alpha.26.2

I am trying this plugin to access strapi data. If I call the APIs with quick succession. It is throwing too many invocation error. Could you please help me how to handle this?

2019-07-05T17:42:50.885Z error: Error: Too many attempts, please try again in a minute.
   at Strapi.request (D:\GitWorkspace\pulse-api\node_modules\strapi-sdk-javascript\src\lib\sdk.ts:99:15)
   at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by lauriejim** [comment]
Hello! 
Are you calling many time Auth routes? 
[Here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/routes.json) routes that have `"policies": ["plugins.users-permissions.ratelimit"],`

I suppose it's the case because this message can be display only for this case.

So [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js) the function that is called and we can see, the config is customizable by editing this [config file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/request.json)

To do that in your project, you will have to follow this [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions)

[This](https://www.npmjs.com/package/koa2-ratelimit) is the node module we use - so you can check available configurations
